// Auto-generated from ISO 3166 (pycountry). Do not edit by hand.
export interface CountryMeta { name: string; iso2: string; flag: string }

export const COUNTRY_META: Record<string, CountryMeta> = {
  ABW: { name: 'Aruba', iso2: 'AW', flag: '🇦🇼' },
  AFG: { name: 'Afghanistan', iso2: 'AF', flag: '🇦🇫' },
  AGO: { name: 'Angola', iso2: 'AO', flag: '🇦🇴' },
  AIA: { name: 'Anguilla', iso2: 'AI', flag: '🇦🇮' },
  ALA: { name: 'Åland Islands', iso2: 'AX', flag: '🇦🇽' },
  ALB: { name: 'Albania', iso2: 'AL', flag: '🇦🇱' },
  AND: { name: 'Andorra', iso2: 'AD', flag: '🇦🇩' },
  ARE: { name: 'United Arab Emirates', iso2: 'AE', flag: '🇦🇪' },
  ARG: { name: 'Argentina', iso2: 'AR', flag: '🇦🇷' },
  ARM: { name: 'Armenia', iso2: 'AM', flag: '🇦🇲' },
  ASM: { name: 'American Samoa', iso2: 'AS', flag: '🇦🇸' },
  ATA: { name: 'Antarctica', iso2: 'AQ', flag: '🇦🇶' },
  ATG: { name: 'Antigua and Barbuda', iso2: 'AG', flag: '🇦🇬' },
  AUS: { name: 'Australia', iso2: 'AU', flag: '🇦🇺' },
  AUT: { name: 'Austria', iso2: 'AT', flag: '🇦🇹' },
  AZE: { name: 'Azerbaijan', iso2: 'AZ', flag: '🇦🇿' },
  BDI: { name: 'Burundi', iso2: 'BI', flag: '🇧🇮' },
  BEL: { name: 'Belgium', iso2: 'BE', flag: '🇧🇪' },
  BEN: { name: 'Benin', iso2: 'BJ', flag: '🇧🇯' },
  BES: { name: 'Bonaire, Sint Eustatius and Saba', iso2: 'BQ', flag: '🇧🇶' },
  BFA: { name: 'Burkina Faso', iso2: 'BF', flag: '🇧🇫' },
  BGD: { name: 'Bangladesh', iso2: 'BD', flag: '🇧🇩' },
  BGR: { name: 'Bulgaria', iso2: 'BG', flag: '🇧🇬' },
  BHR: { name: 'Bahrain', iso2: 'BH', flag: '🇧🇭' },
  BHS: { name: 'Bahamas', iso2: 'BS', flag: '🇧🇸' },
  BIH: { name: 'Bosnia and Herzegovina', iso2: 'BA', flag: '🇧🇦' },
  BLM: { name: 'Saint Barthélemy', iso2: 'BL', flag: '🇧🇱' },
  BLR: { name: 'Belarus', iso2: 'BY', flag: '🇧🇾' },
  BLZ: { name: 'Belize', iso2: 'BZ', flag: '🇧🇿' },
  BMU: { name: 'Bermuda', iso2: 'BM', flag: '🇧🇲' },
  BOL: { name: 'Bolivia, Plurinational State of', iso2: 'BO', flag: '🇧🇴' },
  BRA: { name: 'Brazil', iso2: 'BR', flag: '🇧🇷' },
  BRB: { name: 'Barbados', iso2: 'BB', flag: '🇧🇧' },
  BRN: { name: 'Brunei Darussalam', iso2: 'BN', flag: '🇧🇳' },
  BTN: { name: 'Bhutan', iso2: 'BT', flag: '🇧🇹' },
  BWA: { name: 'Botswana', iso2: 'BW', flag: '🇧🇼' },
  CAF: { name: 'Central African Republic', iso2: 'CF', flag: '🇨🇫' },
  CAN: { name: 'Canada', iso2: 'CA', flag: '🇨🇦' },
  CHE: { name: 'Switzerland', iso2: 'CH', flag: '🇨🇭' },
  CHL: { name: 'Chile', iso2: 'CL', flag: '🇨🇱' },
  CHN: { name: 'China', iso2: 'CN', flag: '🇨🇳' },
  CIV: { name: 'Côte d\'Ivoire', iso2: 'CI', flag: '🇨🇮' },
  CMR: { name: 'Cameroon', iso2: 'CM', flag: '🇨🇲' },
  COD: { name: 'Congo, The Democratic Republic of the', iso2: 'CD', flag: '🇨🇩' },
  COG: { name: 'Congo', iso2: 'CG', flag: '🇨🇬' },
  COK: { name: 'Cook Islands', iso2: 'CK', flag: '🇨🇰' },
  COL: { name: 'Colombia', iso2: 'CO', flag: '🇨🇴' },
  COM: { name: 'Comoros', iso2: 'KM', flag: '🇰🇲' },
  CPV: { name: 'Cabo Verde', iso2: 'CV', flag: '🇨🇻' },
  CRI: { name: 'Costa Rica', iso2: 'CR', flag: '🇨🇷' },
  CUB: { name: 'Cuba', iso2: 'CU', flag: '🇨🇺' },
  CUW: { name: 'Curaçao', iso2: 'CW', flag: '🇨🇼' },
  CYM: { name: 'Cayman Islands', iso2: 'KY', flag: '🇰🇾' },
  CYP: { name: 'Cyprus', iso2: 'CY', flag: '🇨🇾' },
  CZE: { name: 'Czechia', iso2: 'CZ', flag: '🇨🇿' },
  DEU: { name: 'Germany', iso2: 'DE', flag: '🇩🇪' },
  DJI: { name: 'Djibouti', iso2: 'DJ', flag: '🇩🇯' },
  DMA: { name: 'Dominica', iso2: 'DM', flag: '🇩🇲' },
  DNK: { name: 'Denmark', iso2: 'DK', flag: '🇩🇰' },
  DOM: { name: 'Dominican Republic', iso2: 'DO', flag: '🇩🇴' },
  DZA: { name: 'Algeria', iso2: 'DZ', flag: '🇩🇿' },
  ECU: { name: 'Ecuador', iso2: 'EC', flag: '🇪🇨' },
  EGY: { name: 'Egypt', iso2: 'EG', flag: '🇪🇬' },
  ESP: { name: 'Spain', iso2: 'ES', flag: '🇪🇸' },
  EST: { name: 'Estonia', iso2: 'EE', flag: '🇪🇪' },
  ETH: { name: 'Ethiopia', iso2: 'ET', flag: '🇪🇹' },
  FIN: { name: 'Finland', iso2: 'FI', flag: '🇫🇮' },
  FJI: { name: 'Fiji', iso2: 'FJ', flag: '🇫🇯' },
  FLK: { name: 'Falkland Islands (Malvinas)', iso2: 'FK', flag: '🇫🇰' },
  FRA: { name: 'France', iso2: 'FR', flag: '🇫🇷' },
  FRO: { name: 'Faroe Islands', iso2: 'FO', flag: '🇫🇴' },
  FSM: { name: 'Micronesia, Federated States of', iso2: 'FM', flag: '🇫🇲' },
  GAB: { name: 'Gabon', iso2: 'GA', flag: '🇬🇦' },
  GBR: { name: 'United Kingdom', iso2: 'GB', flag: '🇬🇧' },
  GEO: { name: 'Georgia', iso2: 'GE', flag: '🇬🇪' },
  GGY: { name: 'Guernsey', iso2: 'GG', flag: '🇬🇬' },
  GHA: { name: 'Ghana', iso2: 'GH', flag: '🇬🇭' },
  GIB: { name: 'Gibraltar', iso2: 'GI', flag: '🇬🇮' },
  GIN: { name: 'Guinea', iso2: 'GN', flag: '🇬🇳' },
  GLP: { name: 'Guadeloupe', iso2: 'GP', flag: '🇬🇵' },
  GMB: { name: 'Gambia', iso2: 'GM', flag: '🇬🇲' },
  GNB: { name: 'Guinea-Bissau', iso2: 'GW', flag: '🇬🇼' },
  GNQ: { name: 'Equatorial Guinea', iso2: 'GQ', flag: '🇬🇶' },
  GRC: { name: 'Greece', iso2: 'GR', flag: '🇬🇷' },
  GRD: { name: 'Grenada', iso2: 'GD', flag: '🇬🇩' },
  GRL: { name: 'Greenland', iso2: 'GL', flag: '🇬🇱' },
  GTM: { name: 'Guatemala', iso2: 'GT', flag: '🇬🇹' },
  GUF: { name: 'French Guiana', iso2: 'GF', flag: '🇬🇫' },
  GUM: { name: 'Guam', iso2: 'GU', flag: '🇬🇺' },
  GUY: { name: 'Guyana', iso2: 'GY', flag: '🇬🇾' },
  HKG: { name: 'Hong Kong', iso2: 'HK', flag: '🇭🇰' },
  HND: { name: 'Honduras', iso2: 'HN', flag: '🇭🇳' },
  HRV: { name: 'Croatia', iso2: 'HR', flag: '🇭🇷' },
  HTI: { name: 'Haiti', iso2: 'HT', flag: '🇭🇹' },
  HUN: { name: 'Hungary', iso2: 'HU', flag: '🇭🇺' },
  IDN: { name: 'Indonesia', iso2: 'ID', flag: '🇮🇩' },
  IMN: { name: 'Isle of Man', iso2: 'IM', flag: '🇮🇲' },
  IND: { name: 'India', iso2: 'IN', flag: '🇮🇳' },
  IOT: { name: 'British Indian Ocean Territory', iso2: 'IO', flag: '🇮🇴' },
  IRL: { name: 'Ireland', iso2: 'IE', flag: '🇮🇪' },
  IRN: { name: 'Iran, Islamic Republic of', iso2: 'IR', flag: '🇮🇷' },
  IRQ: { name: 'Iraq', iso2: 'IQ', flag: '🇮🇶' },
  ISL: { name: 'Iceland', iso2: 'IS', flag: '🇮🇸' },
  ISR: { name: 'Israel', iso2: 'IL', flag: '🇮🇱' },
  ITA: { name: 'Italy', iso2: 'IT', flag: '🇮🇹' },
  JAM: { name: 'Jamaica', iso2: 'JM', flag: '🇯🇲' },
  JEY: { name: 'Jersey', iso2: 'JE', flag: '🇯🇪' },
  JOR: { name: 'Jordan', iso2: 'JO', flag: '🇯🇴' },
  JPN: { name: 'Japan', iso2: 'JP', flag: '🇯🇵' },
  KAZ: { name: 'Kazakhstan', iso2: 'KZ', flag: '🇰🇿' },
  KEN: { name: 'Kenya', iso2: 'KE', flag: '🇰🇪' },
  KGZ: { name: 'Kyrgyzstan', iso2: 'KG', flag: '🇰🇬' },
  KHM: { name: 'Cambodia', iso2: 'KH', flag: '🇰🇭' },
  KNA: { name: 'Saint Kitts and Nevis', iso2: 'KN', flag: '🇰🇳' },
  KOR: { name: 'Korea, Republic of', iso2: 'KR', flag: '🇰🇷' },
  KWT: { name: 'Kuwait', iso2: 'KW', flag: '🇰🇼' },
  LAO: { name: 'Lao People\'s Democratic Republic', iso2: 'LA', flag: '🇱🇦' },
  LBN: { name: 'Lebanon', iso2: 'LB', flag: '🇱🇧' },
  LBR: { name: 'Liberia', iso2: 'LR', flag: '🇱🇷' },
  LBY: { name: 'Libya', iso2: 'LY', flag: '🇱🇾' },
  LCA: { name: 'Saint Lucia', iso2: 'LC', flag: '🇱🇨' },
  LIE: { name: 'Liechtenstein', iso2: 'LI', flag: '🇱🇮' },
  LKA: { name: 'Sri Lanka', iso2: 'LK', flag: '🇱🇰' },
  LSO: { name: 'Lesotho', iso2: 'LS', flag: '🇱🇸' },
  LTU: { name: 'Lithuania', iso2: 'LT', flag: '🇱🇹' },
  LUX: { name: 'Luxembourg', iso2: 'LU', flag: '🇱🇺' },
  LVA: { name: 'Latvia', iso2: 'LV', flag: '🇱🇻' },
  MAC: { name: 'Macao', iso2: 'MO', flag: '🇲🇴' },
  MAF: { name: 'Saint Martin (French part)', iso2: 'MF', flag: '🇲🇫' },
  MAR: { name: 'Morocco', iso2: 'MA', flag: '🇲🇦' },
  MCO: { name: 'Monaco', iso2: 'MC', flag: '🇲🇨' },
  MDA: { name: 'Moldova, Republic of', iso2: 'MD', flag: '🇲🇩' },
  MDG: { name: 'Madagascar', iso2: 'MG', flag: '🇲🇬' },
  MDV: { name: 'Maldives', iso2: 'MV', flag: '🇲🇻' },
  MEX: { name: 'Mexico', iso2: 'MX', flag: '🇲🇽' },
  MHL: { name: 'Marshall Islands', iso2: 'MH', flag: '🇲🇭' },
  MKD: { name: 'North Macedonia', iso2: 'MK', flag: '🇲🇰' },
  MLI: { name: 'Mali', iso2: 'ML', flag: '🇲🇱' },
  MLT: { name: 'Malta', iso2: 'MT', flag: '🇲🇹' },
  MMR: { name: 'Myanmar', iso2: 'MM', flag: '🇲🇲' },
  MNE: { name: 'Montenegro', iso2: 'ME', flag: '🇲🇪' },
  MNG: { name: 'Mongolia', iso2: 'MN', flag: '🇲🇳' },
  MNP: { name: 'Northern Mariana Islands', iso2: 'MP', flag: '🇲🇵' },
  MOZ: { name: 'Mozambique', iso2: 'MZ', flag: '🇲🇿' },
  MRT: { name: 'Mauritania', iso2: 'MR', flag: '🇲🇷' },
  MTQ: { name: 'Martinique', iso2: 'MQ', flag: '🇲🇶' },
  MUS: { name: 'Mauritius', iso2: 'MU', flag: '🇲🇺' },
  MWI: { name: 'Malawi', iso2: 'MW', flag: '🇲🇼' },
  MYS: { name: 'Malaysia', iso2: 'MY', flag: '🇲🇾' },
  MYT: { name: 'Mayotte', iso2: 'YT', flag: '🇾🇹' },
  NAM: { name: 'Namibia', iso2: 'NA', flag: '🇳🇦' },
  NCL: { name: 'New Caledonia', iso2: 'NC', flag: '🇳🇨' },
  NER: { name: 'Niger', iso2: 'NE', flag: '🇳🇪' },
  NFK: { name: 'Norfolk Island', iso2: 'NF', flag: '🇳🇫' },
  NGA: { name: 'Nigeria', iso2: 'NG', flag: '🇳🇬' },
  NIC: { name: 'Nicaragua', iso2: 'NI', flag: '🇳🇮' },
  NIU: { name: 'Niue', iso2: 'NU', flag: '🇳🇺' },
  NLD: { name: 'Netherlands', iso2: 'NL', flag: '🇳🇱' },
  NOR: { name: 'Norway', iso2: 'NO', flag: '🇳🇴' },
  NPL: { name: 'Nepal', iso2: 'NP', flag: '🇳🇵' },
  NZL: { name: 'New Zealand', iso2: 'NZ', flag: '🇳🇿' },
  OMN: { name: 'Oman', iso2: 'OM', flag: '🇴🇲' },
  PAK: { name: 'Pakistan', iso2: 'PK', flag: '🇵🇰' },
  PAN: { name: 'Panama', iso2: 'PA', flag: '🇵🇦' },
  PER: { name: 'Peru', iso2: 'PE', flag: '🇵🇪' },
  PHL: { name: 'Philippines', iso2: 'PH', flag: '🇵🇭' },
  PLW: { name: 'Palau', iso2: 'PW', flag: '🇵🇼' },
  PNG: { name: 'Papua New Guinea', iso2: 'PG', flag: '🇵🇬' },
  POL: { name: 'Poland', iso2: 'PL', flag: '🇵🇱' },
  PRI: { name: 'Puerto Rico', iso2: 'PR', flag: '🇵🇷' },
  PRK: { name: 'Korea, Democratic People\'s Republic of', iso2: 'KP', flag: '🇰🇵' },
  PRT: { name: 'Portugal', iso2: 'PT', flag: '🇵🇹' },
  PRY: { name: 'Paraguay', iso2: 'PY', flag: '🇵🇾' },
  PSE: { name: 'Palestine, State of', iso2: 'PS', flag: '🇵🇸' },
  PYF: { name: 'French Polynesia', iso2: 'PF', flag: '🇵🇫' },
  QAT: { name: 'Qatar', iso2: 'QA', flag: '🇶🇦' },
  REU: { name: 'Réunion', iso2: 'RE', flag: '🇷🇪' },
  ROU: { name: 'Romania', iso2: 'RO', flag: '🇷🇴' },
  RUS: { name: 'Russian Federation', iso2: 'RU', flag: '🇷🇺' },
  RWA: { name: 'Rwanda', iso2: 'RW', flag: '🇷🇼' },
  SAU: { name: 'Saudi Arabia', iso2: 'SA', flag: '🇸🇦' },
  SDN: { name: 'Sudan', iso2: 'SD', flag: '🇸🇩' },
  SEN: { name: 'Senegal', iso2: 'SN', flag: '🇸🇳' },
  SGP: { name: 'Singapore', iso2: 'SG', flag: '🇸🇬' },
  SLB: { name: 'Solomon Islands', iso2: 'SB', flag: '🇸🇧' },
  SLE: { name: 'Sierra Leone', iso2: 'SL', flag: '🇸🇱' },
  SLV: { name: 'El Salvador', iso2: 'SV', flag: '🇸🇻' },
  SMR: { name: 'San Marino', iso2: 'SM', flag: '🇸🇲' },
  SOM: { name: 'Somalia', iso2: 'SO', flag: '🇸🇴' },
  SPM: { name: 'Saint Pierre and Miquelon', iso2: 'PM', flag: '🇵🇲' },
  SRB: { name: 'Serbia', iso2: 'RS', flag: '🇷🇸' },
  STP: { name: 'Sao Tome and Principe', iso2: 'ST', flag: '🇸🇹' },
  SUR: { name: 'Suriname', iso2: 'SR', flag: '🇸🇷' },
  SVK: { name: 'Slovakia', iso2: 'SK', flag: '🇸🇰' },
  SVN: { name: 'Slovenia', iso2: 'SI', flag: '🇸🇮' },
  SWE: { name: 'Sweden', iso2: 'SE', flag: '🇸🇪' },
  SWZ: { name: 'Eswatini', iso2: 'SZ', flag: '🇸🇿' },
  SXM: { name: 'Sint Maarten (Dutch part)', iso2: 'SX', flag: '🇸🇽' },
  SYC: { name: 'Seychelles', iso2: 'SC', flag: '🇸🇨' },
  SYR: { name: 'Syrian Arab Republic', iso2: 'SY', flag: '🇸🇾' },
  TCA: { name: 'Turks and Caicos Islands', iso2: 'TC', flag: '🇹🇨' },
  TGO: { name: 'Togo', iso2: 'TG', flag: '🇹🇬' },
  THA: { name: 'Thailand', iso2: 'TH', flag: '🇹🇭' },
  TJK: { name: 'Tajikistan', iso2: 'TJ', flag: '🇹🇯' },
  TKM: { name: 'Turkmenistan', iso2: 'TM', flag: '🇹🇲' },
  TLS: { name: 'Timor-Leste', iso2: 'TL', flag: '🇹🇱' },
  TON: { name: 'Tonga', iso2: 'TO', flag: '🇹🇴' },
  TTO: { name: 'Trinidad and Tobago', iso2: 'TT', flag: '🇹🇹' },
  TUN: { name: 'Tunisia', iso2: 'TN', flag: '🇹🇳' },
  TUR: { name: 'Türkiye', iso2: 'TR', flag: '🇹🇷' },
  TWN: { name: 'Taiwan, Province of China', iso2: 'TW', flag: '🇹🇼' },
  TZA: { name: 'Tanzania, United Republic of', iso2: 'TZ', flag: '🇹🇿' },
  UGA: { name: 'Uganda', iso2: 'UG', flag: '🇺🇬' },
  UKR: { name: 'Ukraine', iso2: 'UA', flag: '🇺🇦' },
  URY: { name: 'Uruguay', iso2: 'UY', flag: '🇺🇾' },
  USA: { name: 'United States', iso2: 'US', flag: '🇺🇸' },
  UZB: { name: 'Uzbekistan', iso2: 'UZ', flag: '🇺🇿' },
  VAT: { name: 'Holy See (Vatican City State)', iso2: 'VA', flag: '🇻🇦' },
  VCT: { name: 'Saint Vincent and the Grenadines', iso2: 'VC', flag: '🇻🇨' },
  VEN: { name: 'Venezuela, Bolivarian Republic of', iso2: 'VE', flag: '🇻🇪' },
  VGB: { name: 'Virgin Islands, British', iso2: 'VG', flag: '🇻🇬' },
  VIR: { name: 'Virgin Islands, U.S.', iso2: 'VI', flag: '🇻🇮' },
  VNM: { name: 'Viet Nam', iso2: 'VN', flag: '🇻🇳' },
  VUT: { name: 'Vanuatu', iso2: 'VU', flag: '🇻🇺' },
  YEM: { name: 'Yemen', iso2: 'YE', flag: '🇾🇪' },
  ZAF: { name: 'South Africa', iso2: 'ZA', flag: '🇿🇦' },
  ZMB: { name: 'Zambia', iso2: 'ZM', flag: '🇿🇲' },
  ZWE: { name: 'Zimbabwe', iso2: 'ZW', flag: '🇿🇼' },
};
