// Auto-generated from ISO 3166 (pycountry). Do not edit by hand.
export interface CountryMeta { name: string; flag: string }

export const COUNTRY_META: Record<string, CountryMeta> = {
  ABW: { name: 'Aruba', flag: '🇦🇼' },
  AFG: { name: 'Afghanistan', flag: '🇦🇫' },
  AGO: { name: 'Angola', flag: '🇦🇴' },
  AIA: { name: 'Anguilla', flag: '🇦🇮' },
  ALA: { name: 'Åland Islands', flag: '🇦🇽' },
  ALB: { name: 'Albania', flag: '🇦🇱' },
  AND: { name: 'Andorra', flag: '🇦🇩' },
  ARE: { name: 'United Arab Emirates', flag: '🇦🇪' },
  ARG: { name: 'Argentina', flag: '🇦🇷' },
  ARM: { name: 'Armenia', flag: '🇦🇲' },
  ASM: { name: 'American Samoa', flag: '🇦🇸' },
  ATA: { name: 'Antarctica', flag: '🇦🇶' },
  ATG: { name: 'Antigua and Barbuda', flag: '🇦🇬' },
  AUS: { name: 'Australia', flag: '🇦🇺' },
  AUT: { name: 'Austria', flag: '🇦🇹' },
  AZE: { name: 'Azerbaijan', flag: '🇦🇿' },
  BDI: { name: 'Burundi', flag: '🇧🇮' },
  BEL: { name: 'Belgium', flag: '🇧🇪' },
  BEN: { name: 'Benin', flag: '🇧🇯' },
  BES: { name: 'Bonaire, Sint Eustatius and Saba', flag: '🇧🇶' },
  BFA: { name: 'Burkina Faso', flag: '🇧🇫' },
  BGD: { name: 'Bangladesh', flag: '🇧🇩' },
  BGR: { name: 'Bulgaria', flag: '🇧🇬' },
  BHR: { name: 'Bahrain', flag: '🇧🇭' },
  BHS: { name: 'Bahamas', flag: '🇧🇸' },
  BIH: { name: 'Bosnia and Herzegovina', flag: '🇧🇦' },
  BLM: { name: 'Saint Barthélemy', flag: '🇧🇱' },
  BLR: { name: 'Belarus', flag: '🇧🇾' },
  BLZ: { name: 'Belize', flag: '🇧🇿' },
  BMU: { name: 'Bermuda', flag: '🇧🇲' },
  BOL: { name: 'Bolivia, Plurinational State of', flag: '🇧🇴' },
  BRA: { name: 'Brazil', flag: '🇧🇷' },
  BRB: { name: 'Barbados', flag: '🇧🇧' },
  BRN: { name: 'Brunei Darussalam', flag: '🇧🇳' },
  BTN: { name: 'Bhutan', flag: '🇧🇹' },
  BWA: { name: 'Botswana', flag: '🇧🇼' },
  CAF: { name: 'Central African Republic', flag: '🇨🇫' },
  CAN: { name: 'Canada', flag: '🇨🇦' },
  CHE: { name: 'Switzerland', flag: '🇨🇭' },
  CHL: { name: 'Chile', flag: '🇨🇱' },
  CHN: { name: 'China', flag: '🇨🇳' },
  CIV: { name: 'Côte d\'Ivoire', flag: '🇨🇮' },
  CMR: { name: 'Cameroon', flag: '🇨🇲' },
  COD: { name: 'Congo, The Democratic Republic of the', flag: '🇨🇩' },
  COG: { name: 'Congo', flag: '🇨🇬' },
  COK: { name: 'Cook Islands', flag: '🇨🇰' },
  COL: { name: 'Colombia', flag: '🇨🇴' },
  COM: { name: 'Comoros', flag: '🇰🇲' },
  CPV: { name: 'Cabo Verde', flag: '🇨🇻' },
  CRI: { name: 'Costa Rica', flag: '🇨🇷' },
  CUB: { name: 'Cuba', flag: '🇨🇺' },
  CUW: { name: 'Curaçao', flag: '🇨🇼' },
  CYM: { name: 'Cayman Islands', flag: '🇰🇾' },
  CYP: { name: 'Cyprus', flag: '🇨🇾' },
  CZE: { name: 'Czechia', flag: '🇨🇿' },
  DEU: { name: 'Germany', flag: '🇩🇪' },
  DJI: { name: 'Djibouti', flag: '🇩🇯' },
  DMA: { name: 'Dominica', flag: '🇩🇲' },
  DNK: { name: 'Denmark', flag: '🇩🇰' },
  DOM: { name: 'Dominican Republic', flag: '🇩🇴' },
  DZA: { name: 'Algeria', flag: '🇩🇿' },
  ECU: { name: 'Ecuador', flag: '🇪🇨' },
  EGY: { name: 'Egypt', flag: '🇪🇬' },
  ESP: { name: 'Spain', flag: '🇪🇸' },
  EST: { name: 'Estonia', flag: '🇪🇪' },
  ETH: { name: 'Ethiopia', flag: '🇪🇹' },
  FIN: { name: 'Finland', flag: '🇫🇮' },
  FJI: { name: 'Fiji', flag: '🇫🇯' },
  FLK: { name: 'Falkland Islands (Malvinas)', flag: '🇫🇰' },
  FRA: { name: 'France', flag: '🇫🇷' },
  FRO: { name: 'Faroe Islands', flag: '🇫🇴' },
  FSM: { name: 'Micronesia, Federated States of', flag: '🇫🇲' },
  GAB: { name: 'Gabon', flag: '🇬🇦' },
  GBR: { name: 'United Kingdom', flag: '🇬🇧' },
  GEO: { name: 'Georgia', flag: '🇬🇪' },
  GGY: { name: 'Guernsey', flag: '🇬🇬' },
  GHA: { name: 'Ghana', flag: '🇬🇭' },
  GIB: { name: 'Gibraltar', flag: '🇬🇮' },
  GIN: { name: 'Guinea', flag: '🇬🇳' },
  GLP: { name: 'Guadeloupe', flag: '🇬🇵' },
  GMB: { name: 'Gambia', flag: '🇬🇲' },
  GNB: { name: 'Guinea-Bissau', flag: '🇬🇼' },
  GNQ: { name: 'Equatorial Guinea', flag: '🇬🇶' },
  GRC: { name: 'Greece', flag: '🇬🇷' },
  GRD: { name: 'Grenada', flag: '🇬🇩' },
  GRL: { name: 'Greenland', flag: '🇬🇱' },
  GTM: { name: 'Guatemala', flag: '🇬🇹' },
  GUF: { name: 'French Guiana', flag: '🇬🇫' },
  GUM: { name: 'Guam', flag: '🇬🇺' },
  GUY: { name: 'Guyana', flag: '🇬🇾' },
  HKG: { name: 'Hong Kong', flag: '🇭🇰' },
  HND: { name: 'Honduras', flag: '🇭🇳' },
  HRV: { name: 'Croatia', flag: '🇭🇷' },
  HTI: { name: 'Haiti', flag: '🇭🇹' },
  HUN: { name: 'Hungary', flag: '🇭🇺' },
  IDN: { name: 'Indonesia', flag: '🇮🇩' },
  IMN: { name: 'Isle of Man', flag: '🇮🇲' },
  IND: { name: 'India', flag: '🇮🇳' },
  IOT: { name: 'British Indian Ocean Territory', flag: '🇮🇴' },
  IRL: { name: 'Ireland', flag: '🇮🇪' },
  IRN: { name: 'Iran, Islamic Republic of', flag: '🇮🇷' },
  IRQ: { name: 'Iraq', flag: '🇮🇶' },
  ISL: { name: 'Iceland', flag: '🇮🇸' },
  ISR: { name: 'Israel', flag: '🇮🇱' },
  ITA: { name: 'Italy', flag: '🇮🇹' },
  JAM: { name: 'Jamaica', flag: '🇯🇲' },
  JEY: { name: 'Jersey', flag: '🇯🇪' },
  JOR: { name: 'Jordan', flag: '🇯🇴' },
  JPN: { name: 'Japan', flag: '🇯🇵' },
  KAZ: { name: 'Kazakhstan', flag: '🇰🇿' },
  KEN: { name: 'Kenya', flag: '🇰🇪' },
  KGZ: { name: 'Kyrgyzstan', flag: '🇰🇬' },
  KHM: { name: 'Cambodia', flag: '🇰🇭' },
  KNA: { name: 'Saint Kitts and Nevis', flag: '🇰🇳' },
  KOR: { name: 'Korea, Republic of', flag: '🇰🇷' },
  KWT: { name: 'Kuwait', flag: '🇰🇼' },
  LAO: { name: 'Lao People\'s Democratic Republic', flag: '🇱🇦' },
  LBN: { name: 'Lebanon', flag: '🇱🇧' },
  LBR: { name: 'Liberia', flag: '🇱🇷' },
  LBY: { name: 'Libya', flag: '🇱🇾' },
  LCA: { name: 'Saint Lucia', flag: '🇱🇨' },
  LIE: { name: 'Liechtenstein', flag: '🇱🇮' },
  LKA: { name: 'Sri Lanka', flag: '🇱🇰' },
  LSO: { name: 'Lesotho', flag: '🇱🇸' },
  LTU: { name: 'Lithuania', flag: '🇱🇹' },
  LUX: { name: 'Luxembourg', flag: '🇱🇺' },
  LVA: { name: 'Latvia', flag: '🇱🇻' },
  MAC: { name: 'Macao', flag: '🇲🇴' },
  MAF: { name: 'Saint Martin (French part)', flag: '🇲🇫' },
  MAR: { name: 'Morocco', flag: '🇲🇦' },
  MCO: { name: 'Monaco', flag: '🇲🇨' },
  MDA: { name: 'Moldova, Republic of', flag: '🇲🇩' },
  MDG: { name: 'Madagascar', flag: '🇲🇬' },
  MDV: { name: 'Maldives', flag: '🇲🇻' },
  MEX: { name: 'Mexico', flag: '🇲🇽' },
  MHL: { name: 'Marshall Islands', flag: '🇲🇭' },
  MKD: { name: 'North Macedonia', flag: '🇲🇰' },
  MLI: { name: 'Mali', flag: '🇲🇱' },
  MLT: { name: 'Malta', flag: '🇲🇹' },
  MMR: { name: 'Myanmar', flag: '🇲🇲' },
  MNE: { name: 'Montenegro', flag: '🇲🇪' },
  MNG: { name: 'Mongolia', flag: '🇲🇳' },
  MNP: { name: 'Northern Mariana Islands', flag: '🇲🇵' },
  MOZ: { name: 'Mozambique', flag: '🇲🇿' },
  MRT: { name: 'Mauritania', flag: '🇲🇷' },
  MTQ: { name: 'Martinique', flag: '🇲🇶' },
  MUS: { name: 'Mauritius', flag: '🇲🇺' },
  MWI: { name: 'Malawi', flag: '🇲🇼' },
  MYS: { name: 'Malaysia', flag: '🇲🇾' },
  MYT: { name: 'Mayotte', flag: '🇾🇹' },
  NAM: { name: 'Namibia', flag: '🇳🇦' },
  NCL: { name: 'New Caledonia', flag: '🇳🇨' },
  NER: { name: 'Niger', flag: '🇳🇪' },
  NFK: { name: 'Norfolk Island', flag: '🇳🇫' },
  NGA: { name: 'Nigeria', flag: '🇳🇬' },
  NIC: { name: 'Nicaragua', flag: '🇳🇮' },
  NIU: { name: 'Niue', flag: '🇳🇺' },
  NLD: { name: 'Netherlands', flag: '🇳🇱' },
  NOR: { name: 'Norway', flag: '🇳🇴' },
  NPL: { name: 'Nepal', flag: '🇳🇵' },
  NZL: { name: 'New Zealand', flag: '🇳🇿' },
  OMN: { name: 'Oman', flag: '🇴🇲' },
  PAK: { name: 'Pakistan', flag: '🇵🇰' },
  PAN: { name: 'Panama', flag: '🇵🇦' },
  PER: { name: 'Peru', flag: '🇵🇪' },
  PHL: { name: 'Philippines', flag: '🇵🇭' },
  PLW: { name: 'Palau', flag: '🇵🇼' },
  PNG: { name: 'Papua New Guinea', flag: '🇵🇬' },
  POL: { name: 'Poland', flag: '🇵🇱' },
  PRI: { name: 'Puerto Rico', flag: '🇵🇷' },
  PRK: { name: 'Korea, Democratic People\'s Republic of', flag: '🇰🇵' },
  PRT: { name: 'Portugal', flag: '🇵🇹' },
  PRY: { name: 'Paraguay', flag: '🇵🇾' },
  PSE: { name: 'Palestine, State of', flag: '🇵🇸' },
  PYF: { name: 'French Polynesia', flag: '🇵🇫' },
  QAT: { name: 'Qatar', flag: '🇶🇦' },
  REU: { name: 'Réunion', flag: '🇷🇪' },
  ROU: { name: 'Romania', flag: '🇷🇴' },
  RUS: { name: 'Russian Federation', flag: '🇷🇺' },
  RWA: { name: 'Rwanda', flag: '🇷🇼' },
  SAU: { name: 'Saudi Arabia', flag: '🇸🇦' },
  SDN: { name: 'Sudan', flag: '🇸🇩' },
  SEN: { name: 'Senegal', flag: '🇸🇳' },
  SGP: { name: 'Singapore', flag: '🇸🇬' },
  SLB: { name: 'Solomon Islands', flag: '🇸🇧' },
  SLE: { name: 'Sierra Leone', flag: '🇸🇱' },
  SLV: { name: 'El Salvador', flag: '🇸🇻' },
  SMR: { name: 'San Marino', flag: '🇸🇲' },
  SOM: { name: 'Somalia', flag: '🇸🇴' },
  SPM: { name: 'Saint Pierre and Miquelon', flag: '🇵🇲' },
  SRB: { name: 'Serbia', flag: '🇷🇸' },
  STP: { name: 'Sao Tome and Principe', flag: '🇸🇹' },
  SUR: { name: 'Suriname', flag: '🇸🇷' },
  SVK: { name: 'Slovakia', flag: '🇸🇰' },
  SVN: { name: 'Slovenia', flag: '🇸🇮' },
  SWE: { name: 'Sweden', flag: '🇸🇪' },
  SWZ: { name: 'Eswatini', flag: '🇸🇿' },
  SXM: { name: 'Sint Maarten (Dutch part)', flag: '🇸🇽' },
  SYC: { name: 'Seychelles', flag: '🇸🇨' },
  SYR: { name: 'Syrian Arab Republic', flag: '🇸🇾' },
  TCA: { name: 'Turks and Caicos Islands', flag: '🇹🇨' },
  TGO: { name: 'Togo', flag: '🇹🇬' },
  THA: { name: 'Thailand', flag: '🇹🇭' },
  TJK: { name: 'Tajikistan', flag: '🇹🇯' },
  TKM: { name: 'Turkmenistan', flag: '🇹🇲' },
  TLS: { name: 'Timor-Leste', flag: '🇹🇱' },
  TON: { name: 'Tonga', flag: '🇹🇴' },
  TTO: { name: 'Trinidad and Tobago', flag: '🇹🇹' },
  TUN: { name: 'Tunisia', flag: '🇹🇳' },
  TUR: { name: 'Türkiye', flag: '🇹🇷' },
  TWN: { name: 'Taiwan, Province of China', flag: '🇹🇼' },
  TZA: { name: 'Tanzania, United Republic of', flag: '🇹🇿' },
  UGA: { name: 'Uganda', flag: '🇺🇬' },
  UKR: { name: 'Ukraine', flag: '🇺🇦' },
  URY: { name: 'Uruguay', flag: '🇺🇾' },
  USA: { name: 'United States', flag: '🇺🇸' },
  UZB: { name: 'Uzbekistan', flag: '🇺🇿' },
  VAT: { name: 'Holy See (Vatican City State)', flag: '🇻🇦' },
  VCT: { name: 'Saint Vincent and the Grenadines', flag: '🇻🇨' },
  VEN: { name: 'Venezuela, Bolivarian Republic of', flag: '🇻🇪' },
  VGB: { name: 'Virgin Islands, British', flag: '🇻🇬' },
  VIR: { name: 'Virgin Islands, U.S.', flag: '🇻🇮' },
  VNM: { name: 'Viet Nam', flag: '🇻🇳' },
  VUT: { name: 'Vanuatu', flag: '🇻🇺' },
  YEM: { name: 'Yemen', flag: '🇾🇪' },
  ZAF: { name: 'South Africa', flag: '🇿🇦' },
  ZMB: { name: 'Zambia', flag: '🇿🇲' },
  ZWE: { name: 'Zimbabwe', flag: '🇿🇼' },
};
